### ISSUE TITLE
xmleditor fails to choose root element

### ISSUE THREAD

**Issue by rebornix** [UNC-Libraries/jquery.xmleditor#10]
My schema(xsd) allows users to write xml files with different root element. However if I use this kind of schema in xmleditor, I can't choose root element and "Subelement" is always empty.

**Comment by klopf** [comment]
I had a similar problem... my XML schema defines three possible root elements and I wanted to choose one of them when instantiating the xmleditor.. it was failing to choose one.
Changing the following in xsd/xsd2json.js seems to fix it for my case:
 in function setOriginatingRoot @317
    change != to == and add break:
		if (this.options.rootElement == topLevelElement.name) {
				this.originatingRoot = topLevelElement;
				break;
		}

**Comment by bbpennel** [comment]
That does look like an issue, thank you klopf.  Also, there is a good chance you do not need to specify a rootElement, so it is worth testing without that

**Comment by mccalluc** [comment]
I want to second the advice from @klopf: I am also working with a multi-root schema, and it was crashing on FF with
```
TypeError: topLevelElement is undefined xsd2json.js:317:1
```

Can I just make a PR or is it more complicated than that?

**Comment by bbpennel** [comment]
Yes, turns out that is a bug.  The rootElement option isn't actually needed for a multi-root schema at this point though, so the right approach seems to be to remove the option, which I have now done here:
https://github.com/UNC-Libraries/jquery.xmleditor/commit/5ee0d0a4aca7cf76d127c594bc739af61f88ab93

Could you try with this update and see if it resolves the issue for you?

**Comment by mccalluc** [comment]
Yep, seems to work for me: ran build.js on my schema, made the result into actual json, and tweaked index.html to point at the right file, and my side menu is populating appropriately.

**Comment by bbpennel** [comment]
Excellent!  I am going to mark this issue as closed, but let me know if anything else comes up or you have other comments
