### ISSUE TITLE
CDATA

### ISSUE THREAD

**Issue by upriss** [UNC-Libraries/jquery.xmleditor#18]
I would like to use CDATA in textareas. At the moment it seems that special characters, such as &, are converted even if they are within CDATA when I switch from the gui editor to the text editor. If I load an xml file that contains CDATA funny things happen when I convert between the GUI editor and the text editor (code gets duplicated etc). 

But otherwise: the editor is great! I have been looking for a free tool like this for years. Thank you so much for writing this!

**Comment by lfarrell** [comment]
@upriss It appears that hand editing the escaped characters in the document in the "text" view corrects the issue, which might help you in the short term.  I'll take a look at why it's escaping CDATA content.

**Comment by lfarrell** [comment]
@upriss This issue has been fixed in release 1.1
