### ISSUE TITLE
Is xsd:any supported?

### ISSUE THREAD

**Issue by lsanders** [UNC-Libraries/jquery.xmleditor#20]
I may not understand how this should work, but I expected all of the elements in the "Top Element" list to be available as an "Add Subelement" if my type had an xs:any element.  For example, the mods schema (http://unc-libraries.github.io/jquery.xmleditor/demo/mods.html) has:

```
	<xs:complexType name="extensionDefinition" mixed="true">
		<xs:sequence>
			<xs:any processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="displayLabel" type="xs:string"/>
		<!-- displayLabel added  to <extension> in 3.4. -->
	</xs:complexType>
```

But, if we add an `extension` node, the "Add Subelement" list is empty.

Really cool project, by the way!

**Comment by bbpennel** [comment]
The any tag is roughly supported now since there is the option to add elements not included in the schema, under Add Nodes => Add Element
