### ISSUE TITLE
Missing type in schema

### ISSUE THREAD

**Issue by spbooth** [UNC-Libraries/jquery.xmleditor#21]
The xsd2Json schema parser fails if you have an element without a type

<xsd:element name="Stub"/>

Rightly or wrongly some other schema parsers (e.g. the eclipse schema editor) tend to treat this as anyType so it might be nice to detect this case

**Comment by lfarrell** [comment]
Possibly resolved by fix from issue #28

**Comment by griffofk** [comment]
To fix this problem didn't require xsd2json.js change above ...

      // ---> My Fix
        if(type == null && node.getAttribute("name")=="_Object"){
          type = "anyType";
        }

Just revised the xml, if possible, to include type="xs:anyType" for elements without a type definition.

**Comment by vog** [comment]
I just ran across this, opened a (duplicate) issue #68 and provided an implementation in #70.

**Comment by bbpennel** [comment]
Thank you @vog!
