### ISSUE TITLE
register jquery.xmleditor with bower?

### ISSUE THREAD

**Issue by jenlindner** [UNC-Libraries/jquery.xmleditor#30]
hello! we use jquery.xmleditor in nulib/menu (https://github.com/nulib), we're very happy with it. we'd like to stay up to date with bower, but noticed it's not registered. any chance of that happening? 

cheers,
jen

**Comment by lfarrell** [comment]
Added to Bower as jquery.xmleditor. Currently one version, 1.0.0.
