### ISSUE TITLE
Generated JSON for MODS 3.4 schema incorrect

### ISSUE THREAD

**Issue by whikloj** [UNC-Libraries/jquery.xmleditor#34]
Not sure if I am doing something wrong, but when I download the mods-3.4.xsd (from LoC) and use phantomjs or even the on-the-fly Xsd2Json converter my JSON is different from the stuff available for your [working example](http://unc-libraries.github.io/jquery.xmleditor/demo/mods.html).

The most obvious difference is I can only add one top-level element. Once I add it the UI shows all others as disabled. If I remove the element, then I can add a different one.

I put them in prettydiff.com to give a preview as to the differences.

![json_diff](https://cloud.githubusercontent.com/assets/2857697/7138276/e6507e02-e284-11e4-92a2-1cb1e0f9030e.png)

Any help is appreciated.

**Comment by bbpennel** [comment]
Hmm, thank you, I will look into this.

**Comment by bbpennel** [comment]
This should be fixed for the time being.  It is an issue with the enforcement of maxOccur attributes.  I have disabled that feature for the time being, as it needs revisiting in terms of implementation and whether or not this editor should enforce them or simply provide validation feedback.

https://github.com/UNC-Libraries/jquery.xmleditor/commit/d772ca75f93ccbdc704b92f71a8384dc61bcf6a3

**Comment by whikloj** [comment]
Thanks!
