### ISSUE TITLE
Error converting schema

### ISSUE THREAD

**Issue by ubermichael** [UNC-Libraries/jquery.xmleditor#37]
I'm trying to convert the [TEI-Lite](http://www.tei-c.org/release/xml/tei/custom/schema/xsd/tei_lite.xsd) schema to a json object. I saved it in demo/examples/tei/tei_list.xsd.

When I try to convert it, I receive this error:

```
$ phantomjs build.js ../demo/examples/tei.json ../demo/examples/tei/ tei_lite.xsd
Error: HTTP Error: Unable to import ../demo/examples/tei/tei_lite_dcr.xsd

  file:///Users/mjoyce/Sites/jquery.xmleditor/xsd/xsd2json.js:187 in error
```

There are more lines in the stack trace, but they are mostly minified jquery.

Am I doing anything wrong? How can I debug this problem?

**Comment by bbpennel** [comment]
Looks like you are doing everything right.  The easiest way to debug it is to do so in a web browser, like in this example:

https://github.com/UNC-Libraries/jquery.xmleditor/blob/master/demo/xsd2json_example2.html

However, I worry that I am missing something, but it seems that tei_lite_dcr.xsd  actually has an invalid definition in it.  "base" is a required attribute of xsd:restriction, but dcr:datcat's contains an xsd:restriction without it, which is where the conversion script is failing in this case.  

The schema builds if a null check is added for the base attribute like https://github.com/UNC-Libraries/jquery.xmleditor/commit/4994e9bf26d0a618421a59d46570477836c7c89a.  Feel a bit weird about it though.

**Comment by ubermichael** [comment]
Thanks. I'll try the web browser method.

I'll admit I'm not terribly familiar with the XML Schema spec, but the linked tei_lite.xsd file does validate, at least as far as `xmllint` is concerned.

```
$ xmllint --noout --schema http://www.w3.org/2009/XMLSchema/XMLSchema.xsd tei_lite.xsd 
tei_lite.xsd validates
```

**Comment by ubermichael** [comment]
After checking out 4994e9b, the schema built just fine, and I was able to load a document into the editor.

But now some elements aren't showing up. For example, I cannot add a `p` to a `div` even though that's valid. The document contains `p` elements, but they aren't appearing in the editor at all.

Here's an example: http://www.sfu.ca/~mjoyce/jquery.xmleditor/tei_lite.html

**Comment by bbpennel** [comment]
There also seem to be quite a number of duplicate child elements in the
list.  Not sure what is happening yet, I will need to take a look

**Comment by ubermichael** [comment]
I don't mean to put pressure on anyone, but I was wondering if you've had a chance to look at the problem.

**Comment by nczirjak-acdh** [comment]
Does anyone have a working solution with this TEI? :) If yes, then could you please send it to me? :) Thanks!

**Comment by ubermichael** [comment]
Abandoning this issue.
