### ISSUE TITLE
getting cached content

### ISSUE THREAD

**Issue by ghost** [UNC-Libraries/jquery.xmleditor#39]
After saving XML back to the server, when I go back to editing I am seeing the original document. I assume it has something to do with caching behavior and wondered if anyone observed this and knows the solution.

**Comment by lfarrell** [comment]
I can't seem to replicate this on the UNC setup.  Do you have some sort of caching layer setup on your server?

**Comment by back5576** [comment]
I think it was actually resolved by what I discuss in issue #40
