### ISSUE TITLE
deleting attribute doesn't work

### ISSUE THREAD

**Issue by back5576** [UNC-Libraries/jquery.xmleditor#40]
Document sent to xmlUploadPath still has deleted attribute

**Comment by back5576** [comment]
I fixed with this change:
// Remove an attribute of type objectType from this element
XMLElement.prototype.removeAttribute = function (objectType) {
	this.xmlNode[0].removeAttribute(objectType.localName);
};
Note localName instead of name.  But I don't know if this is a general fix.

**Comment by lfarrell** [comment]
Should be fixed now. Name spaced attributes have to be removed in a different manner from non-name spaced attributes.
