### ISSUE TITLE
Is there a way in jquery.xmleditor to add subelements by default when I am adding a new XML?

### ISSUE THREAD

**Issue by ruchidalal** [UNC-Libraries/jquery.xmleditor#54]
Suppose I have an XML based on XSD:
&lt;patient&gt;
&lt;first&gt;ABC&lt;/first&gt;
&lt;last&gt;XYZ&lt;/last&gt;
&lt;/patient&gt;

Now say I want to add a new patient. I want the first and last elements added by default when I open the xml editor window. I believe that an event is fired on li tag and addChildElementCallback function is called to add the new elements. Not sure how can I trigger for all the &lt;li &gt; tags

**Comment by lsanders** [comment]
I'm also interested in this question. Thanks!

**Comment by bbpennel** [comment]
Hello!  Is the idea that the user would click a link which would cause them to go the xml editor starting from a document contain 1) all existing patients and 2) a new patient with empty `<first>` and `<last>` tags?  Or is the case that in the editor you would want the user to have a "patient" option on the Elements menu, and clicking on it would create the structure `<patient><first /><last /></patient>`?  Or something else?

**Comment by lsanders** [comment]
For my purposes, I'll take the [mods demo](http://unc-libraries.github.io/jquery.xmleditor/demo/mods.html) as an example. The UX I'm looking for is to select the `mods:mods` root node, click `mods:titleInfo` from the right `Add Subelement` dropdown. At that point, it would insert the `mods:titleInfo` and all of the subelements:
`mods:title`
`mods:subTitle`
`mods:partNumber`
`mods:partName`
`mods:nonSort`

From there, a user can populate those without back-and-forth, individual clicking on the subelements.

**Comment by bbpennel** [comment]
This would have to be a new feature of the editor, it doesn't currently support insertion of blocks of elements/attributes.  It would be a very nice one to have if you are interested in contributing.  I'm not able to currently spend much time on new development for the editor unfortunately, but would be happy to give guidance.

**Comment by lsanders** [comment]
Sure @bbpennel, any pointers would be great.
