### ISSUE TITLE
XML code editor drops elements, only text content remains

### ISSUE THREAD

**Issue by shsdev** [UNC-Libraries/jquery.xmleditor#61]
For certain elements (EAD3), the XML code editor ('Text' mode) drops elements, only the text content remains.

Schema used: https://github.com/SAA-SDT/EAD3/blob/master/ead3.xsd

When switching to 'Text' mode, the following XML snippet in EAD3:

```
<fileplan>
    <head>File List</head>
    <fileplan>
        <head>Head Text</head>
        <list listtype="ordered" numeration="upper-roman">
            <item>Text</item>
        </list>
    </fileplan>
</fileplan>
```

is changed to:

```
<fileplan>
    File List
    <fileplan>
        Head Text
        <list listtype="ordered" numeration="upper-roman">
            <item>Text</item>
        </list>
    </fileplan>
</fileplan>
```

The 'head' elements have been dropped, only text remains which leads to non valid EAD3 XML.

This does not happen, if the editor stays in 'XML' mode, then the 'head' elements remain unchanged.

**Comment by bbpennel** [comment]
Extremely late reply, but I am pretty sure this is a case where the browser saw the `<head>` element and interpreted it into the dom, which ends up as whitespace when pulled into the editor.  The simplest solution is to put the initial document into a textarea, like so:

```
  <textarea id="xml_editor">
    <fileplan xmlns="http://ead3.archivists.org/schema/">
        <head>File List</head>
        <fileplan>
            <head>Head Text</head>
            <list listtype="ordered" numeration="upper-roman">
                <item>Text</item>
            </list>
        </fileplan>
    </fileplan>
```
