### ISSUE TITLE
What is the project status of jquery.xmleditor?

### ISSUE THREAD

**Issue by vog** [UNC-Libraries/jquery.xmleditor#65]
I would love to work with this library in my next project.

However, it seems the last activity in this project happened in May 2016, more than one year ago.

What is the current project status of `jquery.xmleditor`?

Are there still active maintainers? Or, is there an effort to include more maintainers in the core team? Or, is there some official  successor project, or fork, that actively pushes forward the development of this codebase?

**Comment by bbpennel** [comment]
UNC Libraries is still actively using the editor in production, and I believe a few projects I know of are.  We have not had a push locally for additional large development and have mostly been adjusting it with new content/configuration in our usage.

We are definitely interested in conversation if there are others that are interested in helping to maintain this or move aspects forward, but don't have a lot of cycles to invest in it presently.  It has simply been a case of new development not being a priority for the maintainers and it currently meeting our needs.

I'm not aware of successors, but would be interested to know about that as well if they are out there.

**Comment by vog** [comment]
Thanks for the fast response!

So I assume that this is still the definite place for collaboration on this code base. Some pull requests are already in the pipeline.
